//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/nukleros/operator-builder-tools/pkg/status"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManager) DeepCopyInto(out *CertManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManager.
func (in *CertManager) DeepCopy() *CertManager {
	if in == nil {
		return nil
	}
	out := new(CertManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerList) DeepCopyInto(out *CertManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerList.
func (in *CertManagerList) DeepCopy() *CertManagerList {
	if in == nil {
		return nil
	}
	out := new(CertManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpec) DeepCopyInto(out *CertManagerSpec) {
	*out = *in
	out.Aws = in.Aws
	out.Injector = in.Injector
	out.Controller = in.Controller
	out.Webhook = in.Webhook
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpec.
func (in *CertManagerSpec) DeepCopy() *CertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecAws) DeepCopyInto(out *CertManagerSpecAws) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecAws.
func (in *CertManagerSpecAws) DeepCopy() *CertManagerSpecAws {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecAws)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecController) DeepCopyInto(out *CertManagerSpecController) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecController.
func (in *CertManagerSpecController) DeepCopy() *CertManagerSpecController {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecControllerResources) DeepCopyInto(out *CertManagerSpecControllerResources) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecControllerResources.
func (in *CertManagerSpecControllerResources) DeepCopy() *CertManagerSpecControllerResources {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecControllerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecControllerResourcesLimits) DeepCopyInto(out *CertManagerSpecControllerResourcesLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecControllerResourcesLimits.
func (in *CertManagerSpecControllerResourcesLimits) DeepCopy() *CertManagerSpecControllerResourcesLimits {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecControllerResourcesLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecControllerResourcesRequests) DeepCopyInto(out *CertManagerSpecControllerResourcesRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecControllerResourcesRequests.
func (in *CertManagerSpecControllerResourcesRequests) DeepCopy() *CertManagerSpecControllerResourcesRequests {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecControllerResourcesRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecInjector) DeepCopyInto(out *CertManagerSpecInjector) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecInjector.
func (in *CertManagerSpecInjector) DeepCopy() *CertManagerSpecInjector {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecInjector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecInjectorResources) DeepCopyInto(out *CertManagerSpecInjectorResources) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecInjectorResources.
func (in *CertManagerSpecInjectorResources) DeepCopy() *CertManagerSpecInjectorResources {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecInjectorResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecInjectorResourcesLimits) DeepCopyInto(out *CertManagerSpecInjectorResourcesLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecInjectorResourcesLimits.
func (in *CertManagerSpecInjectorResourcesLimits) DeepCopy() *CertManagerSpecInjectorResourcesLimits {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecInjectorResourcesLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecInjectorResourcesRequests) DeepCopyInto(out *CertManagerSpecInjectorResourcesRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecInjectorResourcesRequests.
func (in *CertManagerSpecInjectorResourcesRequests) DeepCopy() *CertManagerSpecInjectorResourcesRequests {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecInjectorResourcesRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecWebhook) DeepCopyInto(out *CertManagerSpecWebhook) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecWebhook.
func (in *CertManagerSpecWebhook) DeepCopy() *CertManagerSpecWebhook {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecWebhookResources) DeepCopyInto(out *CertManagerSpecWebhookResources) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecWebhookResources.
func (in *CertManagerSpecWebhookResources) DeepCopy() *CertManagerSpecWebhookResources {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecWebhookResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecWebhookResourcesLimits) DeepCopyInto(out *CertManagerSpecWebhookResourcesLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecWebhookResourcesLimits.
func (in *CertManagerSpecWebhookResourcesLimits) DeepCopy() *CertManagerSpecWebhookResourcesLimits {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecWebhookResourcesLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecWebhookResourcesRequests) DeepCopyInto(out *CertManagerSpecWebhookResourcesRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecWebhookResourcesRequests.
func (in *CertManagerSpecWebhookResourcesRequests) DeepCopy() *CertManagerSpecWebhookResourcesRequests {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecWebhookResourcesRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerStatus) DeepCopyInto(out *CertManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*status.PhaseCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.PhaseCondition)
				**out = **in
			}
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]*status.ChildResource, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.ChildResource)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerStatus.
func (in *CertManagerStatus) DeepCopy() *CertManagerStatus {
	if in == nil {
		return nil
	}
	out := new(CertManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManager) DeepCopyInto(out *TrustManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManager.
func (in *TrustManager) DeepCopy() *TrustManager {
	if in == nil {
		return nil
	}
	out := new(TrustManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrustManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerList) DeepCopyInto(out *TrustManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrustManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerList.
func (in *TrustManagerList) DeepCopy() *TrustManagerList {
	if in == nil {
		return nil
	}
	out := new(TrustManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrustManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpec) DeepCopyInto(out *TrustManagerSpec) {
	*out = *in
	out.Controller = in.Controller
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpec.
func (in *TrustManagerSpec) DeepCopy() *TrustManagerSpec {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpecController) DeepCopyInto(out *TrustManagerSpecController) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpecController.
func (in *TrustManagerSpecController) DeepCopy() *TrustManagerSpecController {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpecController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpecControllerResources) DeepCopyInto(out *TrustManagerSpecControllerResources) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpecControllerResources.
func (in *TrustManagerSpecControllerResources) DeepCopy() *TrustManagerSpecControllerResources {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpecControllerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpecControllerResourcesLimits) DeepCopyInto(out *TrustManagerSpecControllerResourcesLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpecControllerResourcesLimits.
func (in *TrustManagerSpecControllerResourcesLimits) DeepCopy() *TrustManagerSpecControllerResourcesLimits {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpecControllerResourcesLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpecControllerResourcesRequests) DeepCopyInto(out *TrustManagerSpecControllerResourcesRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpecControllerResourcesRequests.
func (in *TrustManagerSpecControllerResourcesRequests) DeepCopy() *TrustManagerSpecControllerResourcesRequests {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpecControllerResourcesRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerStatus) DeepCopyInto(out *TrustManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*status.PhaseCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.PhaseCondition)
				**out = **in
			}
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]*status.ChildResource, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.ChildResource)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerStatus.
func (in *TrustManagerStatus) DeepCopy() *TrustManagerStatus {
	if in == nil {
		return nil
	}
	out := new(TrustManagerStatus)
	in.DeepCopyInto(out)
	return out
}
