//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/nukleros/operator-builder-tools/pkg/status"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManager) DeepCopyInto(out *CertManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManager.
func (in *CertManager) DeepCopy() *CertManager {
	if in == nil {
		return nil
	}
	out := new(CertManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerList) DeepCopyInto(out *CertManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerList.
func (in *CertManagerList) DeepCopy() *CertManagerList {
	if in == nil {
		return nil
	}
	out := new(CertManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpec) DeepCopyInto(out *CertManagerSpec) {
	*out = *in
	out.Aws = in.Aws
	out.CertManager = in.CertManager
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpec.
func (in *CertManagerSpec) DeepCopy() *CertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecAws) DeepCopyInto(out *CertManagerSpecAws) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecAws.
func (in *CertManagerSpecAws) DeepCopy() *CertManagerSpecAws {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecAws)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManager) DeepCopyInto(out *CertManagerSpecCertManager) {
	*out = *in
	out.Injector = in.Injector
	out.Controller = in.Controller
	out.Webhook = in.Webhook
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManager.
func (in *CertManagerSpecCertManager) DeepCopy() *CertManagerSpecCertManager {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerController) DeepCopyInto(out *CertManagerSpecCertManagerController) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerController.
func (in *CertManagerSpecCertManagerController) DeepCopy() *CertManagerSpecCertManagerController {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerControllerResources) DeepCopyInto(out *CertManagerSpecCertManagerControllerResources) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerControllerResources.
func (in *CertManagerSpecCertManagerControllerResources) DeepCopy() *CertManagerSpecCertManagerControllerResources {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerControllerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerControllerResourcesLimits) DeepCopyInto(out *CertManagerSpecCertManagerControllerResourcesLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerControllerResourcesLimits.
func (in *CertManagerSpecCertManagerControllerResourcesLimits) DeepCopy() *CertManagerSpecCertManagerControllerResourcesLimits {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerControllerResourcesLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerControllerResourcesRequests) DeepCopyInto(out *CertManagerSpecCertManagerControllerResourcesRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerControllerResourcesRequests.
func (in *CertManagerSpecCertManagerControllerResourcesRequests) DeepCopy() *CertManagerSpecCertManagerControllerResourcesRequests {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerControllerResourcesRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerInjector) DeepCopyInto(out *CertManagerSpecCertManagerInjector) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerInjector.
func (in *CertManagerSpecCertManagerInjector) DeepCopy() *CertManagerSpecCertManagerInjector {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerInjector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerInjectorResources) DeepCopyInto(out *CertManagerSpecCertManagerInjectorResources) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerInjectorResources.
func (in *CertManagerSpecCertManagerInjectorResources) DeepCopy() *CertManagerSpecCertManagerInjectorResources {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerInjectorResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerInjectorResourcesLimits) DeepCopyInto(out *CertManagerSpecCertManagerInjectorResourcesLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerInjectorResourcesLimits.
func (in *CertManagerSpecCertManagerInjectorResourcesLimits) DeepCopy() *CertManagerSpecCertManagerInjectorResourcesLimits {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerInjectorResourcesLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerInjectorResourcesRequests) DeepCopyInto(out *CertManagerSpecCertManagerInjectorResourcesRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerInjectorResourcesRequests.
func (in *CertManagerSpecCertManagerInjectorResourcesRequests) DeepCopy() *CertManagerSpecCertManagerInjectorResourcesRequests {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerInjectorResourcesRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerWebhook) DeepCopyInto(out *CertManagerSpecCertManagerWebhook) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerWebhook.
func (in *CertManagerSpecCertManagerWebhook) DeepCopy() *CertManagerSpecCertManagerWebhook {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerWebhookResources) DeepCopyInto(out *CertManagerSpecCertManagerWebhookResources) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerWebhookResources.
func (in *CertManagerSpecCertManagerWebhookResources) DeepCopy() *CertManagerSpecCertManagerWebhookResources {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerWebhookResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerWebhookResourcesLimits) DeepCopyInto(out *CertManagerSpecCertManagerWebhookResourcesLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerWebhookResourcesLimits.
func (in *CertManagerSpecCertManagerWebhookResourcesLimits) DeepCopy() *CertManagerSpecCertManagerWebhookResourcesLimits {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerWebhookResourcesLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpecCertManagerWebhookResourcesRequests) DeepCopyInto(out *CertManagerSpecCertManagerWebhookResourcesRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpecCertManagerWebhookResourcesRequests.
func (in *CertManagerSpecCertManagerWebhookResourcesRequests) DeepCopy() *CertManagerSpecCertManagerWebhookResourcesRequests {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpecCertManagerWebhookResourcesRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerStatus) DeepCopyInto(out *CertManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*status.PhaseCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.PhaseCondition)
				**out = **in
			}
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]*status.ChildResource, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.ChildResource)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerStatus.
func (in *CertManagerStatus) DeepCopy() *CertManagerStatus {
	if in == nil {
		return nil
	}
	out := new(CertManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManager) DeepCopyInto(out *TrustManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManager.
func (in *TrustManager) DeepCopy() *TrustManager {
	if in == nil {
		return nil
	}
	out := new(TrustManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrustManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerList) DeepCopyInto(out *TrustManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrustManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerList.
func (in *TrustManagerList) DeepCopy() *TrustManagerList {
	if in == nil {
		return nil
	}
	out := new(TrustManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrustManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpec) DeepCopyInto(out *TrustManagerSpec) {
	*out = *in
	out.TrustManager = in.TrustManager
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpec.
func (in *TrustManagerSpec) DeepCopy() *TrustManagerSpec {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpecTrustManager) DeepCopyInto(out *TrustManagerSpecTrustManager) {
	*out = *in
	out.Controller = in.Controller
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpecTrustManager.
func (in *TrustManagerSpecTrustManager) DeepCopy() *TrustManagerSpecTrustManager {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpecTrustManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpecTrustManagerController) DeepCopyInto(out *TrustManagerSpecTrustManagerController) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpecTrustManagerController.
func (in *TrustManagerSpecTrustManagerController) DeepCopy() *TrustManagerSpecTrustManagerController {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpecTrustManagerController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpecTrustManagerControllerResources) DeepCopyInto(out *TrustManagerSpecTrustManagerControllerResources) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpecTrustManagerControllerResources.
func (in *TrustManagerSpecTrustManagerControllerResources) DeepCopy() *TrustManagerSpecTrustManagerControllerResources {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpecTrustManagerControllerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpecTrustManagerControllerResourcesLimits) DeepCopyInto(out *TrustManagerSpecTrustManagerControllerResourcesLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpecTrustManagerControllerResourcesLimits.
func (in *TrustManagerSpecTrustManagerControllerResourcesLimits) DeepCopy() *TrustManagerSpecTrustManagerControllerResourcesLimits {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpecTrustManagerControllerResourcesLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerSpecTrustManagerControllerResourcesRequests) DeepCopyInto(out *TrustManagerSpecTrustManagerControllerResourcesRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerSpecTrustManagerControllerResourcesRequests.
func (in *TrustManagerSpecTrustManagerControllerResourcesRequests) DeepCopy() *TrustManagerSpecTrustManagerControllerResourcesRequests {
	if in == nil {
		return nil
	}
	out := new(TrustManagerSpecTrustManagerControllerResourcesRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustManagerStatus) DeepCopyInto(out *TrustManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*status.PhaseCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.PhaseCondition)
				**out = **in
			}
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]*status.ChildResource, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(status.ChildResource)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustManagerStatus.
func (in *TrustManagerStatus) DeepCopy() *TrustManagerStatus {
	if in == nil {
		return nil
	}
	out := new(TrustManagerStatus)
	in.DeepCopyInto(out)
	return out
}
