# permissions for end users to view trustmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: capabilities-certificates-operator
    app.kubernetes.io/managed-by: kustomize
  name: certificates-trustmanager-viewer-role
rules:
- apiGroups:
  - certificates.platform.tbd.io
  resources:
  - trustmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.platform.tbd.io
  resources:
  - trustmanagers/status
  verbs:
  - get
