# permissions for end users to edit certmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: capabilities-certificates-operator
    app.kubernetes.io/managed-by: kustomize
  name: certificates-certmanager-editor-role
rules:
- apiGroups:
  - certificates.platform.tbd.io
  resources:
  - certmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certificates.platform.tbd.io
  resources:
  - certmanagers/status
  verbs:
  - get
