apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: capabilities-certificates-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
