---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trust-manager
  namespace: tbd-certificates-system # +operator-builder:field:name=namespace,default="tbd-certificates-system",type=string
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/version: v0.9.2
    app: trust-manager
    app.kubernetes.io/component: trust-manager
    capabilities.tbd.io/capability: certificates
    capabilities.tbd.io/version: v0.0.1
    capabilities.tbd.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: certificates-operator
spec:
  commonName: trust-manager.tbd-certificates-system.svc
  dnsNames:
    - trust-manager
    - trust-manager.tbd-certificates-system
    - trust-manager.tbd-certificates-system.svc
    - trust-manager.tbd-certificates-system.svc.local
  secretName: trust-manager
  revisionHistoryLimit: 1
  issuerRef:
    name: internal
    kind: ClusterIssuer
