---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: trust-manager
  labels:
    app: trust-manager
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/version: v0.9.2
    app.kubernetes.io/component: trust-manager
    capabilities.tbd.io/capability: certificates
    capabilities.tbd.io/version: v0.0.1
    capabilities.tbd.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: certificates-operator
  annotations:
    # +operator-builder:field:name=namespace,type=string,replace="certs-namespace"
    cert-manager.io/inject-ca-from: certs-namespace/trust-manager
webhooks:
  - name: trust.cert-manager.io
    rules:
      - apiGroups:
          - trust.cert-manager.io
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*/*'
    admissionReviewVersions:
      - v1
    timeoutSeconds: 5
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: trust-manager
        namespace: tbd-certificates-system # +operator-builder:field:name=namespace,default="tbd-certificates-system",type=string
        path: /validate-trust-cert-manager-io-v1alpha1-bundle
