apiVersion: certificates.platform.tbd.io/v1alpha1
kind: CertManager
metadata:
  name: certmanager-sample
spec:
  namespace: "tbd-certificates-system"
  aws:
    roleARN: ""
  injector:
    replicas: 2
    image: "quay.io/jetstack/cert-manager-cainjector:v1.14.4"
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        memory: "128Mi"
  controller:
    replicas: 2
    image: "quay.io/jetstack/cert-manager-controller:v1.14.4"
    resources:
      requests:
        cpu: "25m"
        memory: "32Mi"
      limits:
        memory: "64Mi"
  webhook:
    replicas: 2
    image: "quay.io/jetstack/cert-manager-webhook:v1.14.4"
    resources:
      requests:
        cpu: "25m"
        memory: "32Mi"
      limits:
        memory: "64Mi"
