apiVersion: certificates.platform.tbd.io/v1alpha1
kind: TrustManager
metadata:
  name: trustmanager-sample
spec:
  namespace: "tbd-certificates-system"
  controller:
    replicas: 2
    image: "quay.io/jetstack/trust-manager:v0.9.2"
    resources:
      requests:
        cpu: "25m"
        memory: "32Mi"
      limits:
        memory: "64Mi"
